spring:
  application:
    name : springSecurity

  datasource:
    url: jdbc:mysql://localhost:3306/jpadb
    username: chill
    password: chill
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    user:
      name: test
      password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  tomcat:
    threads:
      max: 100 #??? ??? ? ?? ?? ?
      min-spare: 2 #?? ??? ?? ?? ??? ?

jwt:
  secretKey: 12345678901234567890123456789012
  refreshKey: 12345678901234567890123456789012

logging:
  level:
    org:
      springframework:
        security: TRACE

