spring:
  application:
    name : springSecurity

  datasource:
    url: jdbc:mysql://localhost:3306/jpadb
    username: chill
    password: chill
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    user:
      name: jihyun
      password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  tomcat:
    threads:
      max: 100 #??? ??? ? ?? ?? ?
      min-spare: 2 #?? ??? ?? ?? ??? ?


logging:
  level:
    org:
      springframework:
        security: TRACE